journey
    title SaaS Tenant Onboarding
    section Evaluate
      Free Plan: 5: Tenant
    section Subscribe
      Choose a plan: 5: Tenant
      Payment: 5: Tenant
      Create Tenant: 1: Provider
    section Onboard
      Create users: 5: Tenant
      Consume service: 5: Tenant
      
